directory: ~/music
library: ~/music/library.db
import:
    move: true
    quiet_fallback: skip
plugins: convert
convert:
    auto: true
    # tmpdir: /tmp
    command: ffmpeg -y -i $source -q:a 0 $dest
    extension: mp3
    dest: ~/converted
    never_convert_lossy_files: yes
