#!/usr/bin/env fish

set working_dir $(git rev-parse --show-toplevel 2>/dev/null || echo (pwd))
set session $(echo $working_dir | sed 's/\//__/g' | sed 's/\./dot/g' )

if kak -l | rg -q $session
    kak -c $session $argv
else
    kak -s $session $argv
end
