#!/usr/bin/env fish

set working_dir $(git rev-parse --show-toplevel &>/dev/null || pwd)
echo $working_dir
set session $(echo $working_dir | sed 's/\//__/g')
echo $session

if kak -l | rg -q $session
    kak -c $session $argv
else
    kak -s $session $argv
end
