#!/usr/bin/env fish

set launcher_window_id $(niri msg -j windows | jq '.[] | select(.app_id == "fzf-launcher") | .id')

if test -n "$launcher_window_id"
    niri msg action close-window --id "$launcher_window_id"
else
    foot --app-id fzf-launcher -- fzf-launcher
    # kitty --single-instance --app-id fzf-launcher -- fzf-launcher
end
