#! /bin/sh

# display settings
bspc config border_width   2
bspc config window_gap     30
bspc config split_ratio    0.50
bspc config bottom_padding 37

# focus settings
bspc config initial_polarity      second_child
bspc config focus_follows_pointer false
bspc config focus_by_distance     false
bspc config history_aware_focus   true

# pointer settings
bspc config click_to_focus        true
bspc config pointer_follows_focus false
bspc config pointer_modifier      mod1

# monocle settings
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config paddingless_monocle false
bspc config single_monocle      false

# monitor settings
bspc monitor -d i ii iii iv v
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

# color settings
bspc config normal_border_color   '#504945'
bspc config active_border_color   '#504945'
bspc config focused_border_color  '#928374'
bspc config presel_feedback_color '#504945'

# rules
bspc rule -a Zathura state=tiled

# autostart
sxhkd &
polybar main &
